version: 0.2

phases:
  build:
    commands:
       - npm install axios --save
       - npm audit fix --force
       - npm fund
       - npm ci && npm run build # clean install (npm ci) and build (npm run build)

artifacts:
  files:
    - '**/*'
